import type { MockDateParts } from "./types";

/** Fixed "today" so status and renewalDate stay consistent in mock data. */
export const MOCK_TODAY: MockDateParts = { year: 2026, month: 9, day: 20 };

export const CUSTOMERS: readonly string[] = [
  "Acme Corp",
  "Acme Labs",
  "Northwind Ltd",
  "Northwind Retail",
  "Contoso",
  "Contoso Health",
  "Globex",
  "Initech",
  "Umbrella Systems",
  "Stark Analytics",
  "Wayne Logistics",
  "Hooli Cloud",
  "Pied Piper",
  "Massive Dynamic",
  "Soylent Foods",
  "Cyberdyne",
  "Oscorp",
  "Wonka Confectionery",
  "Duff Brewing",
  "Vandelay Industries",
  "Prestige Worldwide",
  "Inversource",
  "Blue Ocean Media",
  "Cedar & Pine",
  "Harbor Freight Co",
  "Lumen Finance",
  "Nimbus Travel",
  "Oak & Iron",
  "Quiet Harbor",
  "Redwood Clinics",
  "Silverline HR",
  "Tidepool Education",
  "Vertex Legal",
  "Willow Parks",
  "Amber Grid",
  "Brightside Insurance",
  "Copperfield Books",
  "Driftwood Hotels",
  "Ember Robotics",
  "Fieldnote Agriculture",
  "Granite Civic",
  "Horizon Biotech",
  "Ivory Coast Coffee",
  "Juniper Networks Demo",
  "Keystone Museums",
  "Larkspur Audio",
  "Maplewood Schools",
  "Nightingale Care",
  "Orchard Payments",
  "Prairie Energy",
];
